targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
      drift_dev:
        options:
          databases:
            my_database: lib/database/database.dart