name: Bug report
description: Create a report to help us address issues you are facing
title: "[Bug] "
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to make us better!

  - type: checkboxes
    id: duplication
    attributes:
      label: ⠀
      options:
        - label: This issue is not duplicated with any other open or closed issues
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: |
        Example:
          App crashes on startup every time after changing settings.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
      placeholder: |
        Example:
          App started normally, everything worked fine.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the bug
      placeholder: |
        Example:
          1. Change "HyperNet Server" to "127.0.1" in "Network" settings
          2. Restart the app
          3. Crash
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Device information
      description: Provide details about your system environment
      placeholder: |
        Example:
          Device: Google Pixel 8 Pro
          System: Baklava (BP22.250124.009)
          Version*: 2.3.2
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: |
        Example:
          setting_items.jpg
          crash_screen.jpg
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here
      placeholder: |
        Crash report or other useful informations
    validations:
      required: false
